<a href="https://colab.research.google.com/github/athrav138/Data-Science-Internship-Soft-Tech-12-Weeks/blob/main/Feature_Engineering_Day_16.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data  = {
    "Name":["Atharv","Shravan","Om","Shree","Tom"],
    "Age":[25,45,34,38,30],
    "Salary":[25000,45000,34000,38000,30000],
    "City":["Sangli","Pune","Miraj","Jaysingpur","Pune"]
}

df = pd.DataFrame(data)
print(df)

      Name  Age  Salary        City
0   Atharv   25   25000      Sangli
1  Shravan   45   45000        Pune
2       Om   34   34000       Miraj
3    Shree   38   38000  Jaysingpur
4      Tom   30   30000        Pune

In [ ]:
df["Age_Group"] = pd.cut(df["Age"],
                        bins = [18,30,40,60],
                         labels = ['Fresher','Junior','Senior'])
print(df)

      Name  Age  Salary        City Age_Group
0   Atharv   25   25000      Sangli   Fresher
1  Shravan   45   45000        Pune    Senior
2       Om   34   34000       Miraj    Junior
3    Shree   38   38000  Jaysingpur    Junior
4      Tom   30   30000        Pune   Fresher

In [ ]:
def salary_categories(sal):
  if sal<=30000:
    return "Low"
  elif sal<=40000:
    return "Medium"
  else:
    return "High"

df["Salary_Category"] = df["Salary"].apply(salary_categories)
df

      Name  Age  Salary        City Age_Group Salary_Category
0   Atharv   25   25000      Sangli   Fresher             Low
1  Shravan   45   45000        Pune    Senior            High
2       Om   34   34000       Miraj    Junior          Medium
3    Shree   38   38000  Jaysingpur    Junior          Medium
4      Tom   30   30000        Pune   Fresher             Low

In [ ]:
city_encoded = pd.get_dummies(df["City"])
print(city_encoded)

   Jaysingpur  Miraj   Pune  Sangli
0       False  False  False    True
1       False  False   True   False
2       False   True  False   False
3        True  False  False   False
4       False  False   True   False

In [ ]:
df["Combined"] = df["Salary"]/df["Age"]
print(df)

      Name  Age  Salary        City Age_Group Salary_Category  Combined
0   Atharv   25   25000      Sangli   Fresher             Low    1000.0
1  Shravan   45   45000        Pune    Senior            High    1000.0
2       Om   34   34000       Miraj    Junior          Medium    1000.0
3    Shree   38   38000  Jaysingpur    Junior          Medium    1000.0
4      Tom   30   30000        Pune   Fresher             Low    1000.0

In [ ]:
from sklearn.preprocessing import MinMaxScaler

scalar = MinMaxScaler()
df["Salary_scale"] = scalar.fit_transform(df[["Salary"]])
df["Age_scale"] = scalar.fit_transform(df[["Age"]])
df

,Name,Age,Salary,City,Age_Group,Salary_Category,Combined,Salary_scale,Age_scale
0,Atharv,25,25000,Sangli,Fresher,Low,1000.0,0.00,0.00
1,Shravan,45,45000,Pune,Senior,High,1000.0,1.00,1.00
2,Om,34,34000,Miraj,Junior,Medium,1000.0,0.45,0.45
3,Shree,38,38000,Jaysingpur,Junior,Medium,1000.0,0.65,0.65
4,Tom,30,30000,Pune,Fresher,Low,1000.0,0.25,0.25

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
df["Salary_scale"] = scaler.fit_transform(df[["Salary"]])
df["Age_scale"] = scaler.fit_transform(df[["Age"]])
df

,Name,Age,Salary,City,Age_Group,Salary_Category,Combined,Salary_scale,Age_scale
0,Atharv,25,25000,Sangli,Fresher,Low,1000.0,-1.376412,-1.376412
1,Shravan,45,45000,Pune,Senior,High,1000.0,1.552125,1.552125
2,Om,34,34000,Miraj,Junior,Medium,1000.0,-0.058571,-0.058571
3,Shree,38,38000,Jaysingpur,Junior,Medium,1000.0,0.527137,0.527137
4,Tom,30,30000,Pune,Fresher,Low,1000.0,-0.644278,-0.644278