<a href="https://colab.research.google.com/github/athrav138/Data-Science-Internship-Soft-Tech-12-Weeks/blob/main/Day_13_Task_Data_Cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [167]:
import pandas as pd
import numpy as np

df = pd.read_csv("dirty-employee.csv")
df

,Employee_ID,Full_Name,Age,Gender,Joining_Date,Department,Salary,Country,Phone,Marks
0,101,Akif Attar,25.0,M,12/2/2026,IT,"?25,000",India,9876543210,85
1,102,Ali Khan,30.0,Male,20-Mar-25,Information Technology,"?30,000",-9876543120,9876543211,90
2,103,Sara Sheikh,NaN,Female,12/5/2020,I.T.,"?28,500",INDIA,(987)6543212,88
3,104,Ahmed Patel,-5.0,male,15-Jan-24,HR,"?35,000",ind,987-654-3213,92
4,105,Fatima Noor,180.0,F,10/8/2023,Finance,"?40,000",Bharat,+91 9876543214,95
5,106,NaN,27.0,Female,NaN,HR,"?27,000",India,9876543215,80
6,107,John Smith,29.0,M,31-12-22,IT,?,India,9876543216,1000
7,108,Priya Sharma,26.0,Female,2024.06.15,Finance,"?26,000",India,NaN,78
8,109,Rahul Verma,31.0,Male,June 10 2023,IT,"?31,000",india,9876543218,82
9,110,Ayesha Khan,28.0,F,1/11/2025,I.T.,"?29,500",INDIA,9876543219,86
10,111,Ali Khan,30.0,Male,20-Mar-25,Information Technology,"?30,000",-9876543120,9876543211,90
11,112,Zoya Shaikh,NaN,female,3/14/2021,HR,"?24,500",India,(987)-654-3220,89
12,113,Imran Sheikh,24.0,M,8/7/2022,I.T.,"?22,000",IND,9876543221,75
13,114,Neha Patil,27.0,Female,5-Jul,2024,?ance,"₹27,500",India,+91 9876543222
14,115,Karan Joshi,29.0,m,30-11-21,Information Technology,"?32,000",Bharat,9876543223,84
15,116,Meera Desai,26.0,Female,15-09-20,IT,"?26,500",India,9876543224,81
16,117,Arjun More,NaN,Male,15-Aug-23,HR,?,INDIA,9876543225,87
17,118,Sneha Kulkarni,23.0,F,8/20/2022,Finance,"?23,000",india,9876543226,79
18,119,Vikram Singh,999.0,Male,10/1/2024,I.T.,"?50,000",India,9876543227,91
19,120,Nida Shaikh,22.0,Female,NaN,Information Technology,"?21,500",IND,9876543228,77

In [168]:
df.describe()

       Employee_ID         Age
count     20.00000   17.000000
mean     110.50000   91.235294
std        5.91608  237.061577
min      101.00000   -5.000000
25%      105.75000   25.000000
50%      110.50000   27.000000
75%      115.25000   30.000000
max      120.00000  999.000000

In [169]:
df["Employee_ID"]

0     101
1     102
2     103
3     104
4     105
5     106
6     107
7     108
8     109
9     110
10    111
11    112
12    113
13    114
14    115
15    116
16    117
17    118
18    119
19    120
Name: Employee_ID, dtype: int64

In [170]:
df.isnull().sum()

Employee_ID     0
Full_Name       1
Age             3
Gender          0
Joining_Date    2
Department      0
Salary          0
Country         0
Phone           1
Marks           0
dtype: int64

In [171]:
df["Full_Name"].fillna("Unknowsn",inplace=True)

/tmp/ipykernel_18820/507131679.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Full_Name"].fillna("Unknowsn",inplace=True)

In [172]:
df["Age"].fillna(df["Age"].mean(),inplace=True)

/tmp/ipykernel_18820/2595122914.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Age"].fillna(df["Age"].mean(),inplace=True)

In [173]:
df["Phone"].fillna("NA",inplace=True)

/tmp/ipykernel_18820/2656477558.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Phone"].fillna("NA",inplace=True)

In [174]:
df["Joining_Date"] = pd.to_datetime(df["Joining_Date"],errors="coerce")
df["Joining_Date"] = df["Joining_Date"].dt.strftime("%Y-%m-%d")

In [176]:

def parse_joining_date(date_str):
    if pd.isna(date_str):
        return pd.NaT

    s = str(date_str).strip()
    if not s or s.lower() == 'nan':
        return pd.NaT

    # List of explicit formats to try
    formats = [
        "%m/%d/%Y",  # e.g., 12/2/2026, 1/11/2025
        "%d-%b-%y",  # e.g., 20-Mar-25, 15-Jan-24
        "%d-%m-%y",  # e.g., 31-12-22, 30-11-21
        "%Y.%m.%d",  # e.g., 2024.06.15
        "%B %d %Y",  # e.g., June 10 2023
        "%b %d %Y",  # e.g., Aug 15 2023
    ]

    for fmt in formats:
        try:
            return pd.to_datetime(s, format=fmt)
        except ValueError:
            continue

    # Fallback: let pandas try to infer without a specific format
    try:
        return pd.to_datetime(s)
    except ValueError:
        return pd.NaT # Return NaT if all attempts fail

# Apply the robust parsing function to the 'Joining_Date' column
df["Joining_Date"] = df["Joining_Date"].apply(parse_joining_date)

# Now df["Joining_Date"] is of datetime64[ns] dtype with NaT for unparseable/missing dates
# We will display the column and its dtype to confirm the change
display(df["Joining_Date"])
display(df["Joining_Date"].dtype)

0    2026-12-02
1           NaT
2    2020-12-05
3           NaT
4    2023-10-08
5           NaT
6           NaT
7           NaT
8           NaT
9    2025-01-11
10          NaT
11   2021-03-14
12   2022-08-07
13          NaT
14          NaT
15          NaT
16          NaT
17   2022-08-20
18   2024-10-01
19          NaT
Name: Joining_Date, dtype: datetime64[ns]

dtype('<M8[ns]')

In [177]:
df['Joining_Date'] = df['Joining_Date'].fillna('2026-06-01')

In [178]:
df.duplicated().sum()

np.int64(0)

In [179]:
df

,Employee_ID,Full_Name,Age,Gender,Joining_Date,Department,Salary,Country,Phone,Marks
0,101,Akif Attar,25.000000,M,2026-12-02,IT,"?25,000",India,9876543210,85
1,102,Ali Khan,30.000000,Male,2026-06-01,Information Technology,"?30,000",-9876543120,9876543211,90
2,103,Sara Sheikh,91.235294,Female,2020-12-05,I.T.,"?28,500",INDIA,(987)6543212,88
3,104,Ahmed Patel,-5.000000,male,2026-06-01,HR,"?35,000",ind,987-654-3213,92
4,105,Fatima Noor,180.000000,F,2023-10-08,Finance,"?40,000",Bharat,+91 9876543214,95
5,106,Unknowsn,27.000000,Female,2026-06-01,HR,"?27,000",India,9876543215,80
6,107,John Smith,29.000000,M,2026-06-01,IT,?,India,9876543216,1000
7,108,Priya Sharma,26.000000,Female,2026-06-01,Finance,"?26,000",India,NA,78
8,109,Rahul Verma,31.000000,Male,2026-06-01,IT,"?31,000",india,9876543218,82
9,110,Ayesha Khan,28.000000,F,2025-01-11,I.T.,"?29,500",INDIA,9876543219,86
10,111,Ali Khan,30.000000,Male,2026-06-01,Information Technology,"?30,000",-9876543120,9876543211,90
11,112,Zoya Shaikh,91.235294,female,2021-03-14,HR,"?24,500",India,(987)-654-3220,89
12,113,Imran Sheikh,24.000000,M,2022-08-07,I.T.,"?22,000",IND,9876543221,75
13,114,Neha Patil,27.000000,Female,2026-06-01,2024,?ance,"₹27,500",India,+91 9876543222
14,115,Karan Joshi,29.000000,m,2026-06-01,Information Technology,"?32,000",Bharat,9876543223,84
15,116,Meera Desai,26.000000,Female,2026-06-01,IT,"?26,500",India,9876543224,81
16,117,Arjun More,91.235294,Male,2026-06-01,HR,?,INDIA,9876543225,87
17,118,Sneha Kulkarni,23.000000,F,2022-08-20,Finance,"?23,000",india,9876543226,79
18,119,Vikram Singh,999.000000,Male,2024-10-01,I.T.,"?50,000",India,9876543227,91
19,120,Nida Shaikh,22.000000,Female,2026-06-01,Information Technology,"?21,500",IND,9876543228,77

In [180]:
median_age = df.loc[(df["Age"] > 0) & (df["Age"] < 125), "Age"].median()

df["Age"] = df["Age"].where(
    (df["Age"] > 0) & (df["Age"] < 125),
    median_age
)

In [181]:
df['Age']=df["Age"].astype(int)

In [182]:
df['Gender'] = df['Gender'].str.title().replace({'M':'Male','F':'Female'})
df['Department'] = df["Department"].str.upper().replace({"INFORMATION TECHNOLOGY":'IT','I.T.':'IT','FINANCE':'FIN','UNKNOWN':'FIN'})

In [183]:
df.dropna(thresh=2,inplace=True)

In [184]:
df

,Employee_ID,Full_Name,Age,Gender,Joining_Date,Department,Salary,Country,Phone,Marks
0,101,Akif Attar,25,Male,2026-12-02,IT,"?25,000",India,9876543210,85
1,102,Ali Khan,30,Male,2026-06-01,IT,"?30,000",-9876543120,9876543211,90
2,103,Sara Sheikh,91,Female,2020-12-05,IT,"?28,500",INDIA,(987)6543212,88
3,104,Ahmed Patel,28,Male,2026-06-01,HR,"?35,000",ind,987-654-3213,92
4,105,Fatima Noor,28,Female,2023-10-08,FIN,"?40,000",Bharat,+91 9876543214,95
5,106,Unknowsn,27,Female,2026-06-01,HR,"?27,000",India,9876543215,80
6,107,John Smith,29,Male,2026-06-01,IT,?,India,9876543216,1000
7,108,Priya Sharma,26,Female,2026-06-01,FIN,"?26,000",India,NA,78
8,109,Rahul Verma,31,Male,2026-06-01,IT,"?31,000",india,9876543218,82
9,110,Ayesha Khan,28,Female,2025-01-11,IT,"?29,500",INDIA,9876543219,86
10,111,Ali Khan,30,Male,2026-06-01,IT,"?30,000",-9876543120,9876543211,90
11,112,Zoya Shaikh,91,Female,2021-03-14,HR,"?24,500",India,(987)-654-3220,89
12,113,Imran Sheikh,24,Male,2022-08-07,IT,"?22,000",IND,9876543221,75
13,114,Neha Patil,27,Female,2026-06-01,2024,?ance,"₹27,500",India,+91 9876543222
14,115,Karan Joshi,29,Male,2026-06-01,IT,"?32,000",Bharat,9876543223,84
15,116,Meera Desai,26,Female,2026-06-01,IT,"?26,500",India,9876543224,81
16,117,Arjun More,91,Male,2026-06-01,HR,?,INDIA,9876543225,87
17,118,Sneha Kulkarni,23,Female,2022-08-20,FIN,"?23,000",india,9876543226,79
18,119,Vikram Singh,28,Male,2024-10-01,IT,"?50,000",India,9876543227,91
19,120,Nida Shaikh,22,Female,2026-06-01,IT,"?21,500",IND,9876543228,77

In [185]:
df['Salary'] = df['Salary'].astype(str).str.replace('?', '', regex=False)
df['Salary'] = df['Salary'].str.replace('ance', '', regex=False)
df['Salary'] = df['Salary'].str.replace(',', '', regex=False)
df['Salary'] = pd.to_numeric(df['Salary'], errors='coerce')
df['Salary'] = df['Salary'].fillna(df['Salary'].mean())

In [186]:
df = df.astype('object')
df.loc[:, "Country"] = "India"

In [187]:
df

,Employee_ID,Full_Name,Age,Gender,Joining_Date,Department,Salary,Country,Phone,Marks
0,101,Akif Attar,25,Male,2026-12-02 00:00:00,IT,25000.0,India,9876543210,85
1,102,Ali Khan,30,Male,2026-06-01 00:00:00,IT,30000.0,India,9876543211,90
2,103,Sara Sheikh,91,Female,2020-12-05 00:00:00,IT,28500.0,India,(987)6543212,88
3,104,Ahmed Patel,28,Male,2026-06-01 00:00:00,HR,35000.0,India,987-654-3213,92
4,105,Fatima Noor,28,Female,2023-10-08 00:00:00,FIN,40000.0,India,+91 9876543214,95
5,106,Unknowsn,27,Female,2026-06-01 00:00:00,HR,27000.0,India,9876543215,80
6,107,John Smith,29,Male,2026-06-01 00:00:00,IT,29500.0,India,9876543216,1000
7,108,Priya Sharma,26,Female,2026-06-01 00:00:00,FIN,26000.0,India,NA,78
8,109,Rahul Verma,31,Male,2026-06-01 00:00:00,IT,31000.0,India,9876543218,82
9,110,Ayesha Khan,28,Female,2025-01-11 00:00:00,IT,29500.0,India,9876543219,86
10,111,Ali Khan,30,Male,2026-06-01 00:00:00,IT,30000.0,India,9876543211,90
11,112,Zoya Shaikh,91,Female,2021-03-14 00:00:00,HR,24500.0,India,(987)-654-3220,89
12,113,Imran Sheikh,24,Male,2022-08-07 00:00:00,IT,22000.0,India,9876543221,75
13,114,Neha Patil,27,Female,2026-06-01 00:00:00,2024,29500.0,India,India,+91 9876543222
14,115,Karan Joshi,29,Male,2026-06-01 00:00:00,IT,32000.0,India,9876543223,84
15,116,Meera Desai,26,Female,2026-06-01 00:00:00,IT,26500.0,India,9876543224,81
16,117,Arjun More,91,Male,2026-06-01 00:00:00,HR,29500.0,India,9876543225,87
17,118,Sneha Kulkarni,23,Female,2022-08-20 00:00:00,FIN,23000.0,India,9876543226,79
18,119,Vikram Singh,28,Male,2024-10-01 00:00:00,IT,50000.0,India,9876543227,91
19,120,Nida Shaikh,22,Female,2026-06-01 00:00:00,IT,21500.0,India,9876543228,77

In [188]:
def clean_phone_number(phone):
    if pd.isna(phone) or phone == 'NA':
        return 'NA'
    phone_str = str(phone)
    # Remove non-numeric characters
    cleaned_phone = ''.join(filter(str.isdigit, phone_str))

    # If the cleaned number is 10 digits long, return it
    if len(cleaned_phone) == 10:
        return cleaned_phone
    # Otherwise, return 'NA'
    return 'NA'

df['Phone'] = df['Phone'].apply(clean_phone_number)

In [189]:
display(df['Phone'])

0     9876543210
1     9876543211
2     9876543212
3     9876543213
4             NA
5     9876543215
6     9876543216
7             NA
8     9876543218
9     9876543219
10    9876543211
11    9876543220
12    9876543221
13            NA
14    9876543223
15    9876543224
16    9876543225
17    9876543226
18    9876543227
19    9876543228
Name: Phone, dtype: object

In [190]:
df

,Employee_ID,Full_Name,Age,Gender,Joining_Date,Department,Salary,Country,Phone,Marks
0,101,Akif Attar,25,Male,2026-12-02 00:00:00,IT,25000.0,India,9876543210,85
1,102,Ali Khan,30,Male,2026-06-01 00:00:00,IT,30000.0,India,9876543211,90
2,103,Sara Sheikh,91,Female,2020-12-05 00:00:00,IT,28500.0,India,9876543212,88
3,104,Ahmed Patel,28,Male,2026-06-01 00:00:00,HR,35000.0,India,9876543213,92
4,105,Fatima Noor,28,Female,2023-10-08 00:00:00,FIN,40000.0,India,NA,95
5,106,Unknowsn,27,Female,2026-06-01 00:00:00,HR,27000.0,India,9876543215,80
6,107,John Smith,29,Male,2026-06-01 00:00:00,IT,29500.0,India,9876543216,1000
7,108,Priya Sharma,26,Female,2026-06-01 00:00:00,FIN,26000.0,India,NA,78
8,109,Rahul Verma,31,Male,2026-06-01 00:00:00,IT,31000.0,India,9876543218,82
9,110,Ayesha Khan,28,Female,2025-01-11 00:00:00,IT,29500.0,India,9876543219,86
10,111,Ali Khan,30,Male,2026-06-01 00:00:00,IT,30000.0,India,9876543211,90
11,112,Zoya Shaikh,91,Female,2021-03-14 00:00:00,HR,24500.0,India,9876543220,89
12,113,Imran Sheikh,24,Male,2022-08-07 00:00:00,IT,22000.0,India,9876543221,75
13,114,Neha Patil,27,Female,2026-06-01 00:00:00,2024,29500.0,India,NA,+91 9876543222
14,115,Karan Joshi,29,Male,2026-06-01 00:00:00,IT,32000.0,India,9876543223,84
15,116,Meera Desai,26,Female,2026-06-01 00:00:00,IT,26500.0,India,9876543224,81
16,117,Arjun More,91,Male,2026-06-01 00:00:00,HR,29500.0,India,9876543225,87
17,118,Sneha Kulkarni,23,Female,2022-08-20 00:00:00,FIN,23000.0,India,9876543226,79
18,119,Vikram Singh,28,Male,2024-10-01 00:00:00,IT,50000.0,India,9876543227,91
19,120,Nida Shaikh,22,Female,2026-06-01 00:00:00,IT,21500.0,India,9876543228,77

In [191]:
# Convert 'Marks' to numeric, coercing errors to NaN
df['Marks'] = pd.to_numeric(df['Marks'], errors='coerce')

# Calculate the mean of valid marks (between 1 and 100)
valid_marks = df.loc[(df['Marks'] >= 1) & (df['Marks'] <= 100), 'Marks']
mean_valid_marks = valid_marks.mean()

# Replace invalid marks (outside 1-100) and NaN with the mean of valid marks
df['Marks'] = df['Marks'].mask((df['Marks'] < 1) | (df['Marks'] > 100) | df['Marks'].isna(), mean_valid_marks)

# Convert 'Marks' to integer type (if appropriate, or keep as float if there are non-integer means)
df['Marks'] = df['Marks'].astype(int)

display(df['Marks'])

0     85
1     90
2     88
3     92
4     95
5     80
6     84
7     78
8     82
9     86
10    90
11    89
12    75
13    84
14    84
15    81
16    87
17    79
18    91
19    77
Name: Marks, dtype: int64

In [193]:
df.to_csv("cleaned_dirty_employee.csv")

In [194]:
df.to_csv("cleaned_dirty_employee1.csv",index=False)