<a href="https://colab.research.google.com/github/athrav138/Data-Science-Internship-Soft-Tech-12-Weeks/blob/main/Project_1_Video_Games_Sales_Cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [59]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler,StandardScaler

In [88]:
# Collecting the dat from CSV File

df = pd.read_csv("vgsales.csv")

In [61]:
df

        Rank  ... Global_Sales
0          1  ...        82.74
1          2  ...        40.24
2          3  ...        35.82
3          4  ...        33.00
4          5  ...        31.37
...      ...  ...          ...
16593  16596  ...         0.01
16594  16597  ...         0.01
16595  16598  ...         0.01
16596  16599  ...         0.01
16597  16600  ...         0.01

[16598 rows x 11 columns]

In [62]:
df.head()
df.tail()

        Rank  ... Global_Sales
16593  16596  ...         0.01
16594  16597  ...         0.01
16595  16598  ...         0.01
16596  16599  ...         0.01
16597  16600  ...         0.01

[5 rows x 11 columns]

In [75]:
df.isnull().sum()

Rank            0
Name            0
Platform        0
Year            0
Genre           0
Publisher       0
NA_Sales        0
EU_Sales        0
JP_Sales        0
Other_Sales     0
Global_Sales    0
dtype: int64

In [85]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 16540 entries, 0 to 16597
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Rank          16540 non-null  int64
 1   Name          16540 non-null  string
 2   Platform      16540 non-null  string
 3   Year          16540 non-null  int64
 4   Genre         16540 non-null  string
 5   Publisher     16540 non-null  string
 6   NA_Sales      16540 non-null  float64
 7   EU_Sales      16540 non-null  float64
 8   JP_Sales      16540 non-null  float64
 9   Other_Sales   16540 non-null  float64
 10  Global_Sales  16540 non-null  float64
dtypes: float64(5), int64(2), string(4)
memory usage: 1.5 MB

In [65]:
df["Name"] = df["Name"].astype('string')
df["Platform"] = df["Platform"].astype('string')
df["Genre"] = df["Genre"].astype('string')
df["Publisher"] = df["Publisher"].astype('string')

In [66]:
df[['Year', 'Publisher']].isnull().all(axis=1).sum()

np.int64(22)

In [67]:
df = df.dropna(
    subset=['Year', 'Publisher'],
    how='all'
)

In [84]:
df[['Year', 'Publisher']].isnull().sum()

Year         0
Publisher    0
dtype: int64

In [82]:
df["Year"] = df["Year"].astype(int)

/tmp/ipykernel_1083/2021913959.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Year"] = df["Year"].astype(int)

In [79]:
df["Year"] = pd.to_numeric(df["Year"])

/tmp/ipykernel_1083/681490206.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Year"] = pd.to_numeric(df["Year"])

In [70]:
df['Year'] = df['Year'].fillna(
    df['Year'].median()
)

/tmp/ipykernel_1083/3102233762.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Year'] = df['Year'].fillna(

In [73]:
df = df.dropna(subset=['Publisher'])

In [77]:
df.describe()

               Rank          Year  ...   Other_Sales  Global_Sales
count  16540.000000  16540.000000  ...  16540.000000  16540.000000
mean    8294.197642   2006.414510  ...      0.048191      0.538426
std     4790.703200      5.788794  ...      0.188879      1.557424
min        1.000000   1980.000000  ...      0.000000      0.010000
25%     4143.750000   2003.000000  ...      0.000000      0.060000
50%     8292.500000   2007.000000  ...      0.010000      0.170000
75%    12440.250000   2010.000000  ...      0.040000      0.480000
max    16600.000000   2020.000000  ...     10.570000     82.740000

[8 rows x 7 columns]

In [83]:
df

        Rank  ... Global_Sales
0          1  ...        82.74
1          2  ...        40.24
2          3  ...        35.82
3          4  ...        33.00
4          5  ...        31.37
...      ...  ...          ...
16593  16596  ...         0.01
16594  16597  ...         0.01
16595  16598  ...         0.01
16596  16599  ...         0.01
16597  16600  ...         0.01

[16540 rows x 11 columns]

In [87]:
df.to_csv("cleaned_vgsales.csv",index=False)