In [1]:
import pandas as pd

In [4]:
dict = {
    "Name":["Atharv","Ram"],
    "Age":[12,17],
    "Salary":[150000,190000]
}

df = pd.DataFrame(dict)
df

     Name  Age  Salary
0  Atharv   12  150000
1     Ram   17  190000

In [6]:
list = [
    ["Atharv","Milind","Suryavanshi"],
    ["Rucha","Milind","Suryavanshi"]
]

df2 = pd.DataFrame(list)
print(df2)

        0       1            2
0  Atharv  Milind  Suryavanshi
1   Rucha  Milind  Suryavanshi

In [7]:
list = [
    ["Atharv","Milind","Suryavanshi"],
    ["Rucha","Milind","Suryavanshi"]
]
col = ["First Name","Middle Name","Last Name"]
df2 = pd.DataFrame(list,columns=col)
print(df2)

  First Name Middle Name    Last Name
0     Atharv      Milind  Suryavanshi
1      Rucha      Milind  Suryavanshi

In [10]:
df2["Age"] = [10,23]
print(df2)

  First Name Middle Name    Last Name  Age
0     Atharv      Milind  Suryavanshi   10
1      Rucha      Milind  Suryavanshi   23

In [11]:
df2

  First Name Middle Name    Last Name  Age
0     Atharv      Milind  Suryavanshi   10
1      Rucha      Milind  Suryavanshi   23

In [12]:
df

     Name  Age  Salary
0  Atharv   10  150000
1     Ram   23  190000

In [13]:
df["Age"]

0    10
1    23
Name: Age, dtype: int64

In [16]:
df.drop('Age',axis=1,inplace=True)

In [17]:
df

     Name  Salary
0  Atharv  150000
1     Ram  190000

In [19]:
df
#df2

     Name  Salary
0  Atharv  150000
1     Ram  190000

In [20]:
df.drop(1,axis=0)

     Name  Salary
0  Atharv  150000

In [21]:
df

     Name  Salary
0  Atharv  150000
1     Ram  190000

In [24]:
df.loc[[0]]

     Name  Salary
0  Atharv  150000

In [25]:
df.iloc[0,1]

np.int64(150000)

In [29]:
df.iloc[1:2,0:2]

  Name  Salary
1  Ram  190000

In [32]:
df[df['Salary']>150000]

  Name  Salary
1  Ram  190000

In [35]:
df[(df['Salary']>150000) & (df['Name']=='Ram')]

  Name  Salary
1  Ram  190000