In [21]:
import numpy as np
import pandas as pd

In [22]:
employees = pd.DataFrame({
    "EmpID": [101, 102, 103, 104],
    "Name": ["John", "Alice", "Bob", "David"],
    "DeptID": [1, 2, 1, 3]
})

In [23]:
departments = pd.DataFrame({
    "DeptID": [1, 2, 3,4],
    "Department": ["HR", "IT", "Finance","Testing"]
})

In [24]:
employees

   EmpID   Name  DeptID
0    101   John       1
1    102  Alice       2
2    103    Bob       1
3    104  David       3

In [25]:
departments

   DeptID Department
0       1         HR
1       2         IT
2       3    Finance
3       4    Testing

In [26]:
pd.merge(employees,departments)

   EmpID   Name  DeptID Department
0    101   John       1         HR
1    102  Alice       2         IT
2    103    Bob       1         HR
3    104  David       3    Finance

In [27]:
pd.merge(employees,departments,on='DeptID')

   EmpID   Name  DeptID Department
0    101   John       1         HR
1    102  Alice       2         IT
2    103    Bob       1         HR
3    104  David       3    Finance

In [28]:
pd.merge(employees,departments,on='DeptID',how='inner')

   EmpID   Name  DeptID Department
0    101   John       1         HR
1    102  Alice       2         IT
2    103    Bob       1         HR
3    104  David       3    Finance

In [29]:
pd.merge(employees,departments,on='DeptID',how='outer')

   EmpID   Name  DeptID Department
0  101.0   John       1         HR
1  103.0    Bob       1         HR
2  102.0  Alice       2         IT
3  104.0  David       3    Finance
4    NaN    NaN       4    Testing

In [34]:
pd.concat((employees,departments))

   EmpID   Name  DeptID Department
0  101.0   John       1        NaN
1  102.0  Alice       2        NaN
2  103.0    Bob       1        NaN
3  104.0  David       3        NaN
0    NaN    NaN       1         HR
1    NaN    NaN       2         IT
2    NaN    NaN       3    Finance
3    NaN    NaN       4    Testing

In [35]:
pd.concat((employees,departments),axis=1)

   EmpID   Name  DeptID  DeptID Department
0    101   John       1       1         HR
1    102  Alice       2       2         IT
2    103    Bob       1       3    Finance
3    104  David       3       4    Testing

In [40]:
employees.set_index('DeptID').join(departments.set_index('DeptID'))

        EmpID   Name Department
DeptID
1         101   John         HR
2         102  Alice         IT
1         103    Bob         HR
3         104  David    Finance