In [ ]:
import pandas as pd
import numpy as np

In [ ]:
dict ={
    "Name": ["Atharv",np.nan,"Rucha"],
    "Age": [ 12,np.nan,45]
}

print(dict)

{'Name': ['Atharv', nan, 'Rucha'], 'Age': [12, nan, 45]}

In [ ]:
df = pd.DataFrame(dict)
print(df)

     Name   Age
0  Atharv  12.0
1     NaN   NaN
2   Rucha  45.0

In [ ]:
df.isna()

    Name    Age
0  False  False
1   True   True
2  False  False

In [ ]:
df.isnull()

    Name    Age
0  False  False
1   True   True
2  False  False

In [ ]:
df.isnull().sum()

Name    1
Age     1
dtype: int64

In [ ]:
df.dropna()

     Name   Age
0  Atharv  12.0
2   Rucha  45.0

In [ ]:
df.fillna(1)

     Name   Age
0  Atharv  12.0
1       1   1.0
2   Rucha  45.0

In [ ]:
values = {"Name":"Milind","Age":143}
df.fillna(values)

     Name    Age
0  Atharv   12.0
1  Milind  143.0
2   Rucha   45.0