In [1]:
import pandas as pd
import numpy as np

In [8]:
data = {
'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
'Store': ['S1', 'S1', 'S2', 'S2', 'S1', '52', 'S2', 'S1'],
'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
'Date': pd.date_range('2023-01-01', periods=8)}

df = pd.DataFrame (data)

In [9]:
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    52    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [17]:
group = df.groupby('Category')
for i,v in group:
  print(i)
  print(v)

A
  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
2        A    S2    150        12 2023-01-03
4        A    S1    120         8 2023-01-05
6        A    S2    200        15 2023-01-07
B
  Category Store  Sales  Quantity       Date
1        B    S1    200        15 2023-01-02
3        B    S2    250        18 2023-01-04
5        B    52    180        20 2023-01-06
7        B    S1    300        25 2023-01-08

In [19]:
df.groupby('Category')['Sales'].sum()

Category
A    570
B    930
Name: Sales, dtype: int64

In [22]:
for i,v in df.groupby(['Category','Store']):
  print(i)
  print(v)

('A', 'S1')
  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
4        A    S1    120         8 2023-01-05
('A', 'S2')
  Category Store  Sales  Quantity       Date
2        A    S2    150        12 2023-01-03
6        A    S2    200        15 2023-01-07
('B', '52')
  Category Store  Sales  Quantity       Date
5        B    52    180        20 2023-01-06
('B', 'S1')
  Category Store  Sales  Quantity       Date
1        B    S1    200        15 2023-01-02
7        B    S1    300        25 2023-01-08
('B', 'S2')
  Category Store  Sales  Quantity       Date
3        B    S2    250        18 2023-01-04

In [24]:
# Aggregations

In [30]:
df['Sales'].agg(['mean','median'])

ValueError: cannot combine transform and aggregation operations