<a href="https://colab.research.google.com/github/athrav138/Data-Science-Internship-Soft-Tech-12-Weeks/blob/main/Project_1_Video_Games_Sales_Feature_Engineering_%26_Scaling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler, StandardScaler

In [21]:
df = pd.read_csv("cleaned_vgsales.csv")

## Feature Engineering Summary

Here's a summary of the feature engineering steps performed:

1.  **Decade_group**: Created a categorical feature from the `Decade` column, grouping years into decades (e.g., '80s', '90s'). This involved careful binning with `right=False` in `pd.cut` to correctly assign boundary years and extending the bins to include 2020.
2.  **Calculated_Sales**: Summed regional sales (`NA_Sales`, `EU_Sales`, `JP_Sales`, `Other_Sales`) to get total sales, which was then compared with `Global_Sales`.
3.  **Top_Region**: Identified the region with the highest sales for each game among `NA_Sales`, `EU_Sales`, `JP_Sales`, and `Other_Sales`.
4.  **Sales_Category**: Categorized `Global_Sales` into 'Low', 'Medium', 'High', and 'Blockbuster' bins.
5.  **Game_Age**: Calculated the age of each game by subtracting its `Year` from 2026.
6.  **NA_Percentage**: Calculated North American sales as a percentage of `Global_Sales`.
7.  **EU_Percentage**: Calculated European sales as a percentage of `Global_Sales`.

In [22]:
df

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
...,...,...,...,...,...,...,...,...,...,...,...
16535,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002,Platform,Kemco,0.01,0.00,0.00,0.00,0.01
16536,16597,Men in Black II: Alien Escape,GC,2003,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01
16537,16598,SCORE International Baja 1000: The Official Game,PS2,2008,Racing,Activision,0.00,0.00,0.00,0.00,0.01
16538,16599,Know How 2,DS,2010,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01
16539,16600,Spirits & Spells,GBA,2003,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01

In [23]:
df["Decade"] = (df["Year"] // 10) * 10
df

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Decade
0,1,Wii Sports,Wii,2006,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74,2000
1,2,Super Mario Bros.,NES,1985,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,1980
2,3,Mario Kart Wii,Wii,2008,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82,2000
3,4,Wii Sports Resort,Wii,2009,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00,2000
4,5,Pokemon Red/Pokemon Blue,GB,1996,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,1990
...,...,...,...,...,...,...,...,...,...,...,...,...
16535,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002,Platform,Kemco,0.01,0.00,0.00,0.00,0.01,2000
16536,16597,Men in Black II: Alien Escape,GC,2003,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01,2000
16537,16598,SCORE International Baja 1000: The Official Game,PS2,2008,Racing,Activision,0.00,0.00,0.00,0.00,0.01,2000
16538,16599,Know How 2,DS,2010,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01,2010
16539,16600,Spirits & Spells,GBA,2003,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01,2000

In [24]:
df["Decade_group"] = pd.cut(df["Decade"], bins=[1980, 1990, 2000, 2010, 2020, 2030], labels=["80s", "90s", "00s", "10s", "20s"], right=False)

df = df.drop(columns=['Decade_group_filled'], errors='ignore')

df

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Decade,Decade_group
0,1,Wii Sports,Wii,2006,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74,2000,00s
1,2,Super Mario Bros.,NES,1985,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,1980,80s
2,3,Mario Kart Wii,Wii,2008,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82,2000,00s
3,4,Wii Sports Resort,Wii,2009,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00,2000,00s
4,5,Pokemon Red/Pokemon Blue,GB,1996,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,1990,90s
...,...,...,...,...,...,...,...,...,...,...,...,...,...
16535,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002,Platform,Kemco,0.01,0.00,0.00,0.00,0.01,2000,00s
16536,16597,Men in Black II: Alien Escape,GC,2003,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01,2000,00s
16537,16598,SCORE International Baja 1000: The Official Game,PS2,2008,Racing,Activision,0.00,0.00,0.00,0.00,0.01,2000,00s
16538,16599,Know How 2,DS,2010,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01,2010,10s
16539,16600,Spirits & Spells,GBA,2003,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01,2000,00s

In [25]:
df

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Decade,Decade_group
0,1,Wii Sports,Wii,2006,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74,2000,00s
1,2,Super Mario Bros.,NES,1985,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,1980,80s
2,3,Mario Kart Wii,Wii,2008,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82,2000,00s
3,4,Wii Sports Resort,Wii,2009,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00,2000,00s
4,5,Pokemon Red/Pokemon Blue,GB,1996,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,1990,90s
...,...,...,...,...,...,...,...,...,...,...,...,...,...
16535,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002,Platform,Kemco,0.01,0.00,0.00,0.00,0.01,2000,00s
16536,16597,Men in Black II: Alien Escape,GC,2003,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01,2000,00s
16537,16598,SCORE International Baja 1000: The Official Game,PS2,2008,Racing,Activision,0.00,0.00,0.00,0.00,0.01,2000,00s
16538,16599,Know How 2,DS,2010,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01,2010,10s
16539,16600,Spirits & Spells,GBA,2003,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01,2000,00s

In [27]:
df["Calculated_Sales"] = (
    df["NA_Sales"]
    + df["EU_Sales"]
    + df["JP_Sales"]
    + df["Other_Sales"]
)

In [28]:
df

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Decade,Decade_group,Calculated_Sales
0,1,Wii Sports,Wii,2006,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74,2000,00s,82.74
1,2,Super Mario Bros.,NES,1985,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,1980,80s,40.24
2,3,Mario Kart Wii,Wii,2008,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82,2000,00s,35.83
3,4,Wii Sports Resort,Wii,2009,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00,2000,00s,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,1990,90s,31.38
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16535,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002,Platform,Kemco,0.01,0.00,0.00,0.00,0.01,2000,00s,0.01
16536,16597,Men in Black II: Alien Escape,GC,2003,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01,2000,00s,0.01
16537,16598,SCORE International Baja 1000: The Official Game,PS2,2008,Racing,Activision,0.00,0.00,0.00,0.00,0.01,2000,00s,0.00
16538,16599,Know How 2,DS,2010,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01,2010,10s,0.01
16539,16600,Spirits & Spells,GBA,2003,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01,2000,00s,0.01

In [29]:
df[["Global_Sales", "Calculated_Sales"]].head()

   Global_Sales  Calculated_Sales
0         82.74             82.74
1         40.24             40.24
2         35.82             35.83
3         33.00             33.00
4         31.37             31.38

In [30]:
df["Top_Region"] = df[
    ["NA_Sales", "EU_Sales", "JP_Sales", "Other_Sales"]
].idxmax(axis=1)

In [31]:
df

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Decade,Decade_group,Calculated_Sales,Top_Region
0,1,Wii Sports,Wii,2006,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74,2000,00s,82.74,NA_Sales
1,2,Super Mario Bros.,NES,1985,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,1980,80s,40.24,NA_Sales
2,3,Mario Kart Wii,Wii,2008,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82,2000,00s,35.83,NA_Sales
3,4,Wii Sports Resort,Wii,2009,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00,2000,00s,33.00,NA_Sales
4,5,Pokemon Red/Pokemon Blue,GB,1996,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,1990,90s,31.38,NA_Sales
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16535,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002,Platform,Kemco,0.01,0.00,0.00,0.00,0.01,2000,00s,0.01,NA_Sales
16536,16597,Men in Black II: Alien Escape,GC,2003,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01,2000,00s,0.01,NA_Sales
16537,16598,SCORE International Baja 1000: The Official Game,PS2,2008,Racing,Activision,0.00,0.00,0.00,0.00,0.01,2000,00s,0.00,NA_Sales
16538,16599,Know How 2,DS,2010,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01,2010,10s,0.01,EU_Sales
16539,16600,Spirits & Spells,GBA,2003,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01,2000,00s,0.01,NA_Sales

In [32]:
df["Top_Region"].value_counts()

Top_Region
NA_Sales       10079
JP_Sales        4016
EU_Sales        2369
Other_Sales       76
Name: count, dtype: int64

In [33]:
df["Sales_Category"] = pd.cut(
    df["Global_Sales"],
    bins=[0, 1, 10, 50, 100],
    labels=["Low", "Medium", "High", "Blockbuster"]
)

In [34]:
df

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Decade,Decade_group,Calculated_Sales,Top_Region,Sales_Category
0,1,Wii Sports,Wii,2006,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74,2000,00s,82.74,NA_Sales,Blockbuster
1,2,Super Mario Bros.,NES,1985,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,1980,80s,40.24,NA_Sales,High
2,3,Mario Kart Wii,Wii,2008,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82,2000,00s,35.83,NA_Sales,High
3,4,Wii Sports Resort,Wii,2009,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00,2000,00s,33.00,NA_Sales,High
4,5,Pokemon Red/Pokemon Blue,GB,1996,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,1990,90s,31.38,NA_Sales,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16535,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002,Platform,Kemco,0.01,0.00,0.00,0.00,0.01,2000,00s,0.01,NA_Sales,Low
16536,16597,Men in Black II: Alien Escape,GC,2003,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01,2000,00s,0.01,NA_Sales,Low
16537,16598,SCORE International Baja 1000: The Official Game,PS2,2008,Racing,Activision,0.00,0.00,0.00,0.00,0.01,2000,00s,0.00,NA_Sales,Low
16538,16599,Know How 2,DS,2010,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01,2010,10s,0.01,EU_Sales,Low
16539,16600,Spirits & Spells,GBA,2003,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01,2000,00s,0.01,NA_Sales,Low

In [35]:
df["Game_Age"] = 2026 - df["Year"]

In [36]:
df

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Decade,Decade_group,Calculated_Sales,Top_Region,Sales_Category,Game_Age
0,1,Wii Sports,Wii,2006,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74,2000,00s,82.74,NA_Sales,Blockbuster,20
1,2,Super Mario Bros.,NES,1985,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,1980,80s,40.24,NA_Sales,High,41
2,3,Mario Kart Wii,Wii,2008,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82,2000,00s,35.83,NA_Sales,High,18
3,4,Wii Sports Resort,Wii,2009,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00,2000,00s,33.00,NA_Sales,High,17
4,5,Pokemon Red/Pokemon Blue,GB,1996,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,1990,90s,31.38,NA_Sales,High,30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16535,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002,Platform,Kemco,0.01,0.00,0.00,0.00,0.01,2000,00s,0.01,NA_Sales,Low,24
16536,16597,Men in Black II: Alien Escape,GC,2003,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01,2000,00s,0.01,NA_Sales,Low,23
16537,16598,SCORE International Baja 1000: The Official Game,PS2,2008,Racing,Activision,0.00,0.00,0.00,0.00,0.01,2000,00s,0.00,NA_Sales,Low,18
16538,16599,Know How 2,DS,2010,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01,2010,10s,0.01,EU_Sales,Low,16
16539,16600,Spirits & Spells,GBA,2003,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01,2000,00s,0.01,NA_Sales,Low,23

In [37]:
df["Game_Age"].describe()

count    16540.000000
mean        19.585490
std          5.788794
min          6.000000
25%         16.000000
50%         19.000000
75%         23.000000
max         46.000000
Name: Game_Age, dtype: float64

In [38]:
df["NA_Percentage"] = (
    df["NA_Sales"] / df["Global_Sales"]
) * 100

In [39]:
df["EU_Percentage"] = (
    df["EU_Sales"] / df["Global_Sales"]
) * 100

In [41]:
df

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Decade,Decade_group,Calculated_Sales,Top_Region,Sales_Category,Game_Age,NA_Percentage,EU_Percentage
0,1,Wii Sports,Wii,2006,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74,2000,00s,82.74,NA_Sales,Blockbuster,20,50.145033,35.073725
1,2,Super Mario Bros.,NES,1985,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,1980,80s,40.24,NA_Sales,High,41,72.266402,8.896620
2,3,Mario Kart Wii,Wii,2008,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82,2000,00s,35.83,NA_Sales,High,18,44.249023,35.957566
3,4,Wii Sports Resort,Wii,2009,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00,2000,00s,33.00,NA_Sales,High,17,47.727273,33.363636
4,5,Pokemon Red/Pokemon Blue,GB,1996,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,1990,90s,31.38,NA_Sales,High,30,35.926044,28.339178
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16535,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002,Platform,Kemco,0.01,0.00,0.00,0.00,0.01,2000,00s,0.01,NA_Sales,Low,24,100.000000,0.000000
16536,16597,Men in Black II: Alien Escape,GC,2003,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01,2000,00s,0.01,NA_Sales,Low,23,100.000000,0.000000
16537,16598,SCORE International Baja 1000: The Official Game,PS2,2008,Racing,Activision,0.00,0.00,0.00,0.00,0.01,2000,00s,0.00,NA_Sales,Low,18,0.000000,0.000000
16538,16599,Know How 2,DS,2010,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01,2010,10s,0.01,EU_Sales,Low,16,0.000000,100.000000
16539,16600,Spirits & Spells,GBA,2003,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01,2000,00s,0.01,NA_Sales,Low,23,100.000000,0.000000

Feature Scaling

In [46]:
scaler = MinMaxScaler()
df["Global_Sales_Scaler"] = scaler.fit_transform(df[["Global_Sales"]])
df["NA_Percentage_Scaler"] = scaler.fit_transform(df[["NA_Percentage"]])
df["EU_Percentage_Scaler"] = scaler.fit_transform(df[["EU_Percentage"]])
df

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,...,Decade_group,Calculated_Sales,Top_Region,Sales_Category,Game_Age,NA_Percentage,EU_Percentage,Global_Sales_Scaler,NA_Percentage_Scaler,EU_Percentage_Scaler
0,1,Wii Sports,Wii,2006,Sports,Nintendo,41.49,29.02,3.77,8.46,...,00s,82.74,NA_Sales,Blockbuster,20,50.145033,35.073725,1.000000,0.501450,0.350737
1,2,Super Mario Bros.,NES,1985,Platform,Nintendo,29.08,3.58,6.81,0.77,...,80s,40.24,NA_Sales,High,41,72.266402,8.896620,0.486281,0.722664,0.088966
2,3,Mario Kart Wii,Wii,2008,Racing,Nintendo,15.85,12.88,3.79,3.31,...,00s,35.83,NA_Sales,High,18,44.249023,35.957566,0.432854,0.442490,0.359576
3,4,Wii Sports Resort,Wii,2009,Sports,Nintendo,15.75,11.01,3.28,2.96,...,00s,33.00,NA_Sales,High,17,47.727273,33.363636,0.398767,0.477273,0.333636
4,5,Pokemon Red/Pokemon Blue,GB,1996,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,...,90s,31.38,NA_Sales,High,30,35.926044,28.339178,0.379064,0.359260,0.283392
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16535,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002,Platform,Kemco,0.01,0.00,0.00,0.00,...,00s,0.01,NA_Sales,Low,24,100.000000,0.000000,0.000000,1.000000,0.000000
16536,16597,Men in Black II: Alien Escape,GC,2003,Shooter,Infogrames,0.01,0.00,0.00,0.00,...,00s,0.01,NA_Sales,Low,23,100.000000,0.000000,0.000000,1.000000,0.000000
16537,16598,SCORE International Baja 1000: The Official Game,PS2,2008,Racing,Activision,0.00,0.00,0.00,0.00,...,00s,0.00,NA_Sales,Low,18,0.000000,0.000000,0.000000,0.000000,0.000000
16538,16599,Know How 2,DS,2010,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,...,10s,0.01,EU_Sales,Low,16,0.000000,100.000000,0.000000,0.000000,1.000000
16539,16600,Spirits & Spells,GBA,2003,Platform,Wanadoo,0.01,0.00,0.00,0.00,...,00s,0.01,NA_Sales,Low,23,100.000000,0.000000,0.000000,1.000000,0.000000

In [47]:
scaler = StandardScaler()
df["Global_Sales_Standard_Scaler"] = scaler.fit_transform(df[["Global_Sales"]])
df["NA_Percentage_Standard_Scaler"] = scaler.fit_transform(df[["NA_Percentage"]])
df["EU_Percentage_Standard_Scaler"] = scaler.fit_transform(df[["EU_Percentage"]])
df

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,...,Sales_Category,Game_Age,NA_Percentage,EU_Percentage,Global_Sales_Scaler,NA_Percentage_Scaler,EU_Percentage_Scaler,Global_Sales_Standard_Scaler,NA_Percentage_Standard_Scaler,EU_Percentage_Standard_Scaler
0,1,Wii Sports,Wii,2006,Sports,Nintendo,41.49,29.02,3.77,8.46,...,Blockbuster,20,50.145033,35.073725,1.000000,0.501450,0.350737,52.782080,0.134444,0.489543
1,2,Super Mario Bros.,NES,1985,Platform,Nintendo,29.08,3.58,6.81,0.77,...,High,41,72.266402,8.896620,0.486281,0.722664,0.088966,25.492598,0.783659,-0.562215
2,3,Mario Kart Wii,Wii,2008,Racing,Nintendo,15.85,12.88,3.79,3.31,...,High,18,44.249023,35.957566,0.432854,0.442490,0.359576,22.654492,-0.038592,0.525054
3,4,Wii Sports Resort,Wii,2009,Sports,Nintendo,15.75,11.01,3.28,2.96,...,High,17,47.727273,33.363636,0.398767,0.477273,0.333636,20.843754,0.063488,0.420834
4,5,Pokemon Red/Pokemon Blue,GB,1996,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,...,High,30,35.926044,28.339178,0.379064,0.359260,0.283392,19.797122,-0.282854,0.218959
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16535,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002,Platform,Kemco,0.01,0.00,0.00,0.00,...,Low,24,100.000000,0.000000,0.000000,1.000000,0.000000,-0.339305,1.597582,-0.919668
16536,16597,Men in Black II: Alien Escape,GC,2003,Shooter,Infogrames,0.01,0.00,0.00,0.00,...,Low,23,100.000000,0.000000,0.000000,1.000000,0.000000,-0.339305,1.597582,-0.919668
16537,16598,SCORE International Baja 1000: The Official Game,PS2,2008,Racing,Activision,0.00,0.00,0.00,0.00,...,Low,18,0.000000,0.000000,0.000000,0.000000,0.000000,-0.339305,-1.337207,-0.919668
16538,16599,Know How 2,DS,2010,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,...,Low,16,0.000000,100.000000,0.000000,0.000000,1.000000,-0.339305,-1.337207,3.098185
16539,16600,Spirits & Spells,GBA,2003,Platform,Wanadoo,0.01,0.00,0.00,0.00,...,Low,23,100.000000,0.000000,0.000000,1.000000,0.000000,-0.339305,1.597582,-0.919668

In [48]:
df.to_csv("feature_vgsales.csv",index=False)